server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}
        
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full
        decode404: false

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
  
---
spring:
  profiles: producao
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/